"""Make sequence_id nullable and add user_id to Variable

Revision ID: 016d442b5c52
Revises: d0bb526b7da4
Create Date: 2025-06-22 15:07:08.878126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '016d442b5c52'
down_revision: Union[str, Sequence[str], None] = 'd0bb526b7da4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variables', sa.Column('user_id', sa.Integer(), nullable=False))
    op.alter_column('variables', 'sequence_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint('_user_var_name_uc', 'variables', ['name', 'user_id', 'sequence_id'])
    op.create_foreign_key(None, 'variables', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'variables', type_='foreignkey')
    op.drop_constraint('_user_var_name_uc', 'variables', type_='unique')
    op.alter_column('variables', 'sequence_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('variables', 'user_id')
    # ### end Alembic commands ###
