"""recreate variables table with lowercase enum

Revision ID: e2a5d2dbacba
Revises: 7af96c838b6f
Create Date: 2025-06-28 14:55:04.970882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2a5d2dbacba'
down_revision: Union[str, Sequence[str], None] = '7af96c838b6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('variables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('GLOBAL', 'INPUT', 'OUTPUT', name='variabletypeenum'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sequence_id', sa.Integer(), nullable=True),
    sa.Column('value_json', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sequence_id'], ['sequences.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'sequence_id', name='_sequence_variable_name_uc'),
    sa.UniqueConstraint('name', 'user_id', 'sequence_id', name='_user_var_name_uc')
    )
    op.create_index(op.f('ix_variables_id'), 'variables', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_variables_id'), table_name='variables')
    op.drop_table('variables')
    # ### end Alembic commands ###
