"""msg

Revision ID: f567cabf31c2
Revises: 3c2aa6e750ef
Create Date: 2025-06-26 02:42:02.486171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f567cabf31c2'
down_revision: Union[str, Sequence[str], None] = '3c2aa6e750ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('global_list_items', 'value',
        existing_type=sa.Text(),
        type_=sa.JSON(),
        postgresql_using='value::json',   # <-- ADD THIS!
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('global_list_items', 'value',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
